name: flutter_app_1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  carousel_slider: ^5.1.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-VariableFont_wght.ttf
  assets:
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/4.png
